### ISSUE TITLE
source_digest instead of source?

### ISSUE THREAD

**Issue by tecywiz121** [JoakimSoderberg/coveralls-cmake#1]
I believe coveralls switched from uploading the entire source, to just uploading the MD5. I've tried fixed it myself, but I can't seem to get coveralls to display any information at all.

**Comment by JoakimSoderberg** [comment]
Hello,

I'm not really following, do you mean you have tried using this project, and cannot get it to work? Or did you mean you have tried changing it not to send the entire source?

**Comment by JoakimSoderberg** [comment]
Ok I did some snooping and found this:
https://github.com/tecywiz121/libclowder/commit/04668c0525a059b694d8a6971b421e7aa3969ef1

Actually, them not sending the source is nice... That's kind of been the biggest headache of mine.... Properly escaping JSON strings using the CMake language = Not fun.

**Comment by JoakimSoderberg** [comment]
Your changes kind of breaks other stuff due to how you did them... Anyway, I will try to fix this as soon as I get some time over. Thanks for the heads up... I always thought it was stupid to have to send the source as a json string :)

**Comment by tecywiz121** [comment]
Oh I'm quite aware, my changes are pretty much just a quick hack to get it to work.
Great project by the way, thanks for putting it together!
On Mar 10, 2015 4:40 PM, =?ISO-8859-1?Q?Joakim_S=F6derberg?= notifications@github.com wrote:Your changes kind of breaks other stuff due to how you did them... Anyway, I will try to fix this as soon as I get some time over. Thanks for the heads up... I always thought it was stupid to have to send the source as a json string :)

**Comment by JoakimSoderberg** [comment]
Thanks, you're the first user I know of, except me... :)

Hmm, I'm not sure why it won't work... But I can't say the coveralls API docs are especially good. So I don't know if this can be trusted:
https://coveralls.zendesk.com/hc/en-us/articles/201774865-API-Introduction

``` json
{
  "service_job_id": "1234567890",
  "service_name": "travis-ci",
  "source_files": [
    {
      "name": "example.rb",
      "source_digest": "asdfasdf1234asfasdf2345",
      "coverage": [null, 1, null]
    },
    {
      "name": "lib/two.rb",
      "source_digest": "asdf1234asdfsdfggsfgd9423",
      "coverage": [null, 1, 0, null]
    }
  ]
}
```

And then my example project:

``` json
{
  "service_name": "travis-ci",
  "service_job_id": "",
  "source_files": [  {
      "name": "complicated.c",
      "source_digest": "107867eb3439f46b2fb1415284df7550",
      "coverage": [null, null, 6, null, 6, null, 4, null, 2, null, 0, null, null, 2, 6, null]
  }]
}
```

Make sure CMake has the correct MD5 sum:

``` bash
$ md5 /Users/js/dev/coveralls-cmake-example/complicated.c
MD5 (/Users/js/dev/coveralls-cmake-example/complicated.c) = 107867eb3439f46b2fb1415284df7550
```

Everything runs fine: https://travis-ci.org/JoakimSoderberg/coveralls-cmake-example/builds/53864482

But then nothing: https://coveralls.io/jobs/4839092

So I guess it doesn't work :)

I will revert my changes, and ask coveralls support... Are you having problems with using this script the "old" way?

**Comment by JoakimSoderberg** [comment]
haha what... I was a but quick there... now I see .. IT DID work :) so I was a bit fast to revert my changes.

It was that I quickly opened the coveralls page and saw it wasn't there.. but it has some load time :)

**Comment by JoakimSoderberg** [comment]
So this is fixed now :)
