### ISSUE TITLE
problem getting the right coverage for header files

### ISSUE THREAD

**Issue by onqtam** [JoakimSoderberg/coveralls-cmake#11]
This might not be a real issue but more like a call for help:

I have managed to get a minimal example working but I cannot find the problem in my a-bit-more-complex setup as described [here](http://stackoverflow.com/questions/35248421/trouble-getting-the-right-coverage-for-header-files)

Also I had to use the env var exports to get the uploading working

```
- export COVERALLS_SERVICE_NAME=travis-ci
- export COVERALLS_REPO_TOKEN=abc12345
```

and it even didn't work a few times!

**Comment by JoakimSoderberg** [comment]
Hello,

Regarding the upload, yes that is how you need to do it if you upload locally. I have only ever bothered with it being uploaded via Travis-CI where it is automatic.

I cloned and tried to compile your repository, but I could not (OSX). So I cannot look at the output myself.
I have never tried coverage for CPP header code like this, but I guess it should not matter.

One idea is to look in the *.gcov files that you will find in the build dir... Are those similarly screwed up?

But you are not following the example. Is it even possible to force a debug build like you're doing in CMakeLists.txt like that?

``` cmake
set(CMAKE_BUILD_TYPE Debug CACHE STRING "" FORCE)
```

And if you do not build in debug mode, coverage info will not be reliable...

**Comment by onqtam** [comment]
Yea it is possible to set the build type like that - even the compiler can be overridden.
Anyway asking this was a long shot - just in case you had any idea... I will try again going from a simple working example towards my real use case. Thanks.

**Comment by onqtam** [comment]
OMFG!!!!!! I found the problem!

had to use `include_directories("${CMAKE_SOURCE_DIR}/doctest/")` instead of `include_directories("../../doctest/")`

nice usage of 10+ hours... You can add a section in the readme that for header files no relative include paths (going up in the folder hierarchy) should be used

**Comment by JoakimSoderberg** [comment]
ah yes, never used relative paths in CMake :|

Well hopefully 10 hours with at least some new knowledge, and probably som insight in other things that will help you in other ways down the road ;) Good you solved it
