### ISSUE TITLE
{"message":"Couldn't find a repository matching this job.","error":true}

### ISSUE THREAD

**Issue by agauniyal** [JoakimSoderberg/coveralls-cmake#14]
I've tried everything, exporting those two tokens, Logging in and out of github as well as coveralls and travis ci, readding repo to travis as well as coveralls. But this error still occurs.

https://travis-ci.org/agauniyal/rang

**Comment by agauniyal** [comment]
Occurs b/w lines 380-400, 389 to be exact if you choose gcc-4.8.

**Comment by jslee02** [comment]
Have you tried [this](https://github.com/JoakimSoderberg/coveralls-cmake#faq)? It worked for [my case](https://github.com/dartsim/dart/blob/master/.travis.yml#L19). It seems the token always needs to be specified whether the repo is private or not.

**Comment by agauniyal** [comment]
@jslee02 , first suggestion didn't worked but specifying the token did :smile: thanks for your help.

**Comment by JoakimSoderberg** [comment]
Ok good that this got resolved :)

**Comment by Godzil** [comment]
It is still broken, and I suppose it is because the upload part does not support the latest way to send data to covealls. The JSON format seems to have changed if I read their documentation: https://docs.codecov.io/v4.3.0/reference#upload
