### ISSUE TITLE
Out of source builds?

### ISSUE THREAD

**Issue by laprej** [JoakimSoderberg/coveralls-cmake#2]
Hi,

It seems like out of source builds somehow break this?  I get an error like this:
# Generate JSON for files:

CMake Error at /tmp/ROSS/core/cmake/CoverallsGenerateGcov.cmake:392 (file):
  file STRINGS file "/tmp/ROSS-x/core/queue/splay.c" cannot be read.

But my code is in /tmp/ROSS/core/queue/splay.c (notice no '-x' on the ROSS directory).

**Comment by JoakimSoderberg** [comment]
I would need some background exactly what you're trying to do. Command line and such...

I use out of source builds all the time and it works fine. When you all of a sudden get an incorrect path like that, I would rather suspect something fishy with your CMake cache.

``` bash
cd /tmp/ROSS
mkdir build
cd build
rm -rf * # Make sure this dir is completely clean!
cmake ..
```

is that what you're doing? Are you following the example: https://github.com/JoakimSoderberg/coveralls-cmake-example
