### ISSUE TITLE
clean target should remove generated files

### ISSUE THREAD

**Issue by fsaintjacques** [JoakimSoderberg/coveralls-cmake#4]

**Comment by JoakimSoderberg** [comment]
Hello,

Could you be a bit more specific on what you mean?

Maybe you could create a pull request with change if possible?

Here are some relevant links:
http://www.cmake.org/cmake/help/v2.8.8/cmake.html#command%3aset_directory_properties

Clean targets are not "first class citizens" in cmake. `make clean` is specific for the Makefile generator:
http://www.cmake.org/pipermail/cmake/2006-October/011477.html

Instead normally to do a clean build in cmake, you delete your build directory. You should use the "out of source" build concept.

**Comment by fsaintjacques** [comment]
I'm a bit new to cmake, didn't know 'clean' was a target only for make. Point taken!

**Comment by JoakimSoderberg** [comment]
Ok :)
