### ISSUE TITLE
support multiple gcov binary

### ISSUE THREAD

**Issue by fsaintjacques** [JoakimSoderberg/coveralls-cmake#5]
I need to point to a specific GCOV executable (see matrix build of https://travis-ci.org/fsaintjacques/disruptor-- and https://coveralls.io/r/fsaintjacques/disruptor--). For now I'm simply exporting GCOV environment variable.

```
if (NOT DEFINED ENV{GCOV})
  find_program(GCOV_EXECUTABLE gcov)
else()
  find_program(GCOV_EXECUTABLE $ENV{GCOV})
endif()
```

This is not the most elegant way of doing it, but my cmake-foo is lacking.

**Comment by JoakimSoderberg** [comment]
@fsaintjacques sorry I had completely missed this... You should've created a Pull Request so I can just merge your change :)

Seems like @urdh has forked and made  commit for this, I told him to create a Pull Request from his change:
https://github.com/urdh/coveralls-cmake/commit/444c22bdf6352503df0a2395f5717b0b532d29b2

**Comment by urdh** [comment]
Pull request coming up in a bit.
