### ISSUE TITLE
JSON not uploaded

### ISSUE THREAD

**Issue by anderflash** [JoakimSoderberg/coveralls-cmake#9]
Hi,

How can I resolve this?

``` json
{"message":"Couldn't find a repository matching this job.","error":true}
```

The [Travis build](https://travis-ci.org/grafeo/grafeo/builds/78693041)
The [.travis.yml](https://github.com/grafeo/grafeo/blob/feature-5/.travis.yml)
The [CMakeLists.txt](https://github.com/grafeo/grafeo/blob/feature-5/CMakeLists.txt)
Thanks

**Comment by JoakimSoderberg** [comment]
Hello!

Well have you most importantly enabled your project on http://coveralls.io/ ? And what is the URL there. Since the error is from coveralls itself.

**Comment by anderflash** [comment]
Well, I've enabled it:
https://coveralls.io/github/grafeo/grafeo

But I can't remove the 0% status. Where I can put this URL?

Thanks

**Comment by JoakimSoderberg** [comment]
Well you shouldn't have to mention it... it should just work by magic on Travis if you repo is enabled in coveralls. My script runs fine, so I think the issue is elsewhere. Can't see any apparent errors in your configs either... Seems this is a repo where people with similar errors have opened issues. Maybe ask there? :/   https://github.com/lemurheavy/coveralls-public

https://github.com/lemurheavy/coveralls-public/issues/279 <--same problem for instance.

**Comment by anderflash** [comment]
@cmaurer answer in [lemurheavy/coveralls-public#279](https://github.com/lemurheavy/coveralls-public/issues/279) helped me.

``` bash
- export COVERALLS_SERVICE_NAME=travis-ci
- export COVERALLS_REPO_TOKEN=abc12345
```

I think the coveralls-cmake tutorial could mention the need to set the `COVERALLS_REPO_TOKEN` environment variable before running `cmake` and `make`.

Now I see the code coverity. Thank you very much!

**Comment by JoakimSoderberg** [comment]
Ok, good you solved it :) Hmmm that's weird, I'll add a note about it in the [README.md](README.md) but I haven't needed to do that on any of my projects...

Btw, a tip is http://codecov.io/ it's a lot easier to setup and has a lot more features and, most importantly has a lot more stable servers (coveralls server have really bad response times at times).

**Comment by anderflash** [comment]
I found why you don't need to insert the token and I needed it: because you put the token in "Environment Variable" settings of Travis CI. So, we don't need to put the token inside .travis.yml, just put in this site section. I set the environment variable and removed the statement in .travis.yml, and it worked.

Even though, you could mention the two possibilities: 
- set the `COVERALLS_REPO_TOKEN` inside `.travis.yml`
- set the `COVERALLS_REPO_TOKEN` inside **Environment Variable** section in _repo settings_ of Travis CI

**Comment by JoakimSoderberg** [comment]
Actually I have done none of those things, it just happens automatically for me... Weird
